version: '3.8'

services:
  web:
    build: .
    volumes:
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - DEBUG=False
    depends_on:
      - db
      - redis
    networks:
      - heyb-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - heyb-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - heyb-network

  celery:
    build: .
    command: celery -A heyb worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env.prod
    environment:
      - DEBUG=False
    depends_on:
      - db
      - redis
    networks:
      - heyb-network

  celery-beat:
    build: .
    command: celery -A heyb beat -l INFO
    volumes:
      - .:/app
    env_file:
      - .env.prod
    environment:
      - DEBUG=False
    depends_on:
      - db
      - redis
    networks:
      - heyb-network

networks:
  heyb-network:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
