services:
  # 웹 서비스 정의
  - type: web
    name: heyb-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn heyb.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        fromDatabase:
          name: heyb-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: heyb-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: heyb-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: heyb-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: heyb-db
          property: port

  # Redis 서비스
  - type: redis
    name: heyb-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

  # 워커 서비스 (Celery)
  - type: worker
    name: heyb-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A heyb worker -l INFO
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        fromService:
          type: web
          name: heyb-web
          envVarKey: SECRET_KEY
      - key: REDIS_URL
        fromService:
          type: redis
          name: heyb-redis
          envVarKey: REDIS_URL
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: heyb-redis
          envVarKey: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: heyb-redis
          envVarKey: REDIS_URL
      - key: DB_NAME
        fromDatabase:
          name: heyb-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: heyb-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: heyb-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: heyb-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: heyb-db
          property: port

  # Celery Beat 서비스
  - type: worker
    name: heyb-celery-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A heyb beat -l INFO
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        fromService:
          type: web
          name: heyb-web
          envVarKey: SECRET_KEY
      - key: REDIS_URL
        fromService:
          type: redis
          name: heyb-redis
          envVarKey: REDIS_URL
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: heyb-redis
          envVarKey: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: heyb-redis
          envVarKey: REDIS_URL

# 데이터베이스 정의
databases:
  - name: heyb-db
    plan: free
