# k8s/overlays/prod/ghcr-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZG9uZy1wYXJrIiwicGFzc3dvcmQiOiJnaHBfVjR4clg2VFoyUk96ZkphSThPWGI1a2xYVUVmekgxNFdtcjFjIiwiYXV0aCI6IlpHOXVaeTF3WVhKck9tZG9jRjlXTkhoeVdEWlVXakpTVDNwbVNtRkpPRTlZWWpWcmJGaFZSV1o2U0RFMFYyMXlNV009In19fQ==%