apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heyb-prod

resources:
  - ../../base
  - namespace.yaml
  - secrets.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

replicas:
  - name: heyb-web
    count: 2
  - name: heyb-celery
    count: 2
  - name: heyb-celery-beat
    count: 1

images:
  - name: ${IMAGE_REGISTRY}/heyb-web
    newName: ${IMAGE_REGISTRY}/heyb-web
    newTag: ${IMAGE_TAG} 