apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heyb-prod

resources:
  - ../../base
  - namespace.yaml
  - secrets.yaml
  - media-hostpath-pv.yaml

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

replicas:
  - name: heyb-web
    count: 2
  - name: heyb-celery
    count: 2
  - name: heyb-celery-beat
    count: 1

images:
  - name: ghcr.io/co-heyb/heyb-web
    newName: ghcr.io/co-heyb/heyb-web
    newTag: latest 