apiVersion: apps/v1
kind: Deployment
metadata:
  name: heyb-celery
  labels:
    app: heyb
    component: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heyb
      component: celery
  template:
    metadata:
      labels:
        app: heyb
        component: celery
    spec:
      containers:
      - name: celery
        image: ghcr.io/co-heyb/heyb-web:latest
        command: ["celery", "-A", "heyb", "worker", "-l", "INFO"]
        env:
        - name: DEBUG
          value: "False"
        envFrom:
        - secretRef:
            name: heyb-secrets
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: heyb-media-pvc 