apiVersion: apps/v1
kind: Deployment
metadata:
  name: heyb-db
  labels:
    app: heyb
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heyb
      component: db
  template:
    metadata:
      labels:
        app: heyb
        component: db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: heyb-secrets
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: heyb-secrets
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: heyb-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: heyb-secrets
              key: DB_PASSWORD
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: heyb-postgres-pvc 