apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heyb-postgres-pvc
  labels:
    app: heyb
    component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 