apiVersion: apps/v1
kind: Deployment
metadata:
  name: heyb-web
  labels:
    app: heyb
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heyb
      component: web
  template:
    metadata:
      labels:
        app: heyb
        component: web
      annotations:
        deploy-date: "{{ date }}"  # kustomize에서 자동으로 현재 시간으로 변환됨
    spec:
      serviceAccountName: heyb-sa
      containers:
      - name: web
        image: ghcr.io/co-heyb/heyb-web:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: PORT
          value: "8000"
        - name: STATIC_VERSION
          value: "{{ date }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: heyb-secrets
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: heyb-media-pvc 