apiVersion: apps/v1
kind: Deployment
metadata:
  name: heyb-web
  labels:
    app: heyb
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heyb
      component: web
  template:
    metadata:
      labels:
        app: heyb
        component: web
    spec:
      serviceAccountName: heyb-sa
      containers:
      - name: web
        image: ghcr.io/co-heyb/heyb-web:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: PORT
          value: "8000"
        envFrom:
        - secretRef:
            name: heyb-secrets
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: static-volume
          mountPath: /app/staticfiles
        - name: media-volume
          mountPath: /app/media
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: static-volume
          mountPath: /usr/share/nginx/html/static
        - name: media-volume
          mountPath: /usr/share/nginx/html/media
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: heyb-static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: heyb-media-pvc
      - name: nginx-config
        configMap:
          name: nginx-static-config 