apiVersion: apps/v1
kind: Deployment
metadata:
  name: heyb-web
  labels:
    app: heyb
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heyb
      component: web
  template:
    metadata:
      labels:
        app: heyb
        component: web
      annotations:
        deploy-date: "{{ date }}"  # kustomize에서 자동으로 현재 시간으로 변환됨
    spec:
      serviceAccountName: heyb-sa
      containers:
      - name: web
        image: ghcr.io/co-heyb/heyb-web:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: PORT
          value: "8000"
        - name: STATIC_VERSION
          value: "{{ date }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: heyb-secrets
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        # 미디어 볼륨 마운트 복원
        volumeMounts:
        - name: media-volume
          mountPath: /app/media
        - name: static-volume
          mountPath: /app/staticfiles
      
      # Nginx 컨테이너 추가 - 정적/미디어 파일 서빙
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: media-volume
          mountPath: /usr/share/nginx/html/media
        - name: static-volume
          mountPath: /usr/share/nginx/html/static
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      
      # 미디어 볼륨 정의 복원
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: heyb-media-pvc
      - name: static-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-static-config 