apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
  - db-deployment.yaml
  - db-service.yaml
  - db-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-pvc.yaml
  - celery-deployment.yaml
  - celery-beat-deployment.yaml
  - serviceaccount.yaml

# 날짜 변환 설정 추가
replacements:
  - source:
      kind: Deployment
      name: heyb-web
      fieldPath: metadata.annotations.[date]
    targets:
      - select:
          kind: Deployment
          name: heyb-web
        fieldPaths:
          - metadata.annotations.deploy-date
        options:
          create: true

patches:
  - target:
      kind: Deployment
      name: heyb-web
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          date: "$(date +%Y%m%d%H%M%S)"

# commonLabels:
#   app: heyb

# 시크릿은 환경별로 다르게 생성됩니다 