apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-static-config
  labels:
    app: heyb
    component: nginx-static
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # 정적 파일 캐싱 비활성화 (개발용)
      # 프로덕션에서는 적절한 캐싱 정책 사용 필요
      location /static/ {
        alias /usr/share/nginx/html/static/;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Last-Modified $date_gmt;
        add_header Pragma "no-cache";
        add_header X-Static-Version $http_x_static_version;
      }

      location /media/ {
        alias /usr/share/nginx/html/media/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
      }

      # 나머지 요청은 Django 앱으로 프록시
      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Static-Version $http_x_static_version;
      }
    } 