apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heyb-static-pvc
  labels:
    app: heyb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heyb-media-pvc
  labels:
    app: heyb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 