apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heyb-redis-pvc
  labels:
    app: heyb
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 