apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heyb-dev

resources:
  - ../../base
  - namespace.yaml
  - secrets.yaml
  # registry-secret.yaml 파일은 민감한 정보를 포함하고 있어 Git에 저장하지 않습니다.
  # 실제 배포 시 별도로 적용해야 합니다.
  # - registry-secret.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

replicas:
  - name: heyb-web
    count: 1
  - name: heyb-celery
    count: 1
  - name: heyb-celery-beat
    count: 1

images:
  - name: ghcr.io/co-heyb/heyb-web
    newName: ghcr.io/co-heyb/heyb-web
    newTag: latest 