apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heyb-dev

resources:
  - ../../base
  - namespace.yaml
  - secrets.yaml
  - registry-secret.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

replicas:
  - name: heyb-web
    count: 1
  - name: heyb-celery
    count: 1
  - name: heyb-celery-beat
    count: 1

images:
  - name: ghcr.io/co-heyb/heyb-web
    newName: ghcr.io/co-heyb/heyb-web
    newTag: latest 