apiVersion: v1
kind: Secret
metadata:
  name: heyb-secrets
type: Opaque
stringData:
  # 데이터베이스 설정
  DB_HOST: heyb-db
  DB_PORT: "5432"
  DB_NAME: heyb
  DB_USER: heyb
  DB_PASSWORD: dev-password-change-me
  
  # Django 설정
  SECRET_KEY: dev-secret-key-change-me
  ALLOWED_HOSTS: "*"
  
  # Redis 설정
  REDIS_HOST: heyb-redis
  REDIS_PORT: "6379"
  
  # 이메일 설정
  EMAIL_HOST: smtp.example.com
  EMAIL_PORT: "587"
  EMAIL_HOST_USER: user@example.com
  EMAIL_HOST_PASSWORD: email-password-change-me
  
  # 기타 설정
  AWS_ACCESS_KEY_ID: aws-key-change-me
  AWS_SECRET_ACCESS_KEY: aws-secret-change-me
  AWS_STORAGE_BUCKET_NAME: heyb-dev-bucket 